CREATE USER DEMO_USER IDENTIFIED BY "replace_with_demo_password" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE TO DEMO_USER;


-- Create a table for image metadata + vector
CREATE TABLE DEMO_USER.image_vectors (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name  VARCHAR2(4000),
    bucket_name  VARCHAR2(255),
    namespace    VARCHAR2(255),
    embedding    VECTOR(1024, FLOAT32),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE UNIQUE INDEX DEMO_USER.image_vectors_u1
    ON DEMO_USER.image_vectors (namespace, bucket_name, object_name);

-- Create this after loading enough demo data, if approximate search is desired.
-- CREATE VECTOR INDEX DEMO_USER.image_vectors_hnsw_idx
--     ON DEMO_USER.image_vectors (embedding)
--     ORGANIZATION INMEMORY NEIGHBOR GRAPH
--     DISTANCE COSINE
--     WITH TARGET ACCURACY 90;

EXIT;
